baseurl = "astro.atosc.org"
title = "Stars and Astrophotography"
languageCode = "en-US"
theme = "hugo-icarus"
paginate = 5

# temporary values for build
ignorecache = true
builddrafts = false
verbose = true

# Enable comments by entering your Disqus shortname
disqusShortname = "astro-atosc"

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you're
    author = "Hugues Obolonsky"
    bio = "IT manager - DevOps Astrophotographer"
    location = "Paris / Earth"
    site_description = "Astrophotography"
    copyright  = "HoxCa | Powered by [Hugo](//gohugo.io)."

    # Enable Google Analytics by entering your tracking code
    google_analytics = "UA-70503045-1"

    # Format dates with Go's time formating
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

#[[params.menu]]
#    before = false
#    label  = "Tags"
#    link   = "tags/"

#[[params.menu]]
#    before = false
#    label  = "Categories"
#    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/intent/follow?&region=follow_link&screen_name=hoxca&tw_p=followbutton"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = true
    tags = true
    tag_cloud = false

[params.social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = "channel/UCIb_sQJGpkNYVoJJ8A-GHaQ"
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "ossadvocate"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "hoxca"
